# Generated by Django 5.2.5 on 2025-10-14 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conciliacion', models.DateField()),
                ('pasarela', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('CONCILIADO', 'Conciliado'), ('CON_DIFERENCIAS', 'Con Diferencias')], default='PENDIENTE', max_length=20)),
                ('match_sistema', models.IntegerField(default=0)),
                ('diferencias', models.IntegerField(default=0)),
                ('sin_match', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=20, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Validación'), ('VALIDADO', 'Validado Correctamente'), ('RECHAZADO', 'Rechazado'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error en Proceso')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo')], max_length=20)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estudiante_nombre', models.CharField(max_length=200)),
                ('concepto', models.CharField(max_length=200)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_referencia', models.CharField(max_length=20, unique=True)),
                ('tipo_incidencia', models.CharField(choices=[('DIF_MONTO', 'Diferencia de Monto'), ('SIN_MATCH', 'Sin Match'), ('DUPLICADO', 'Pago Duplicado'), ('MONTO_ALTO', 'Monto Alto'), ('AJUSTE', 'Ajuste'), ('ANULACION', 'Anulación')], max_length=20)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('PENDIENTE_FIRMA', 'Pendiente de Firma')], default='ABIERTA', max_length=20)),
                ('descripcion', models.TextField()),
                ('monto_diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('justificacion', models.TextField(blank=True)),
                ('conciliacion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validacion.conciliacion')),
                ('usuario_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pago_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validacion.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.estado')),
            ],
        ),
        migrations.CreateModel(
            name='TablaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('importancia', models.IntegerField(default=1)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.estado')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severidad', models.CharField(choices=[('Info', 'Informativa'), ('Warning', 'Advertencia'), ('Critica', 'Crítica')], max_length=10)),
                ('registro_afectado', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('detalle', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado_gestion', models.BooleanField(default=False)),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tabla_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.tablasistema')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.estado')),
                ('tabla_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.tablasistema')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registro_afectado', models.IntegerField()),
                ('valores_nuevos', models.JSONField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tabla_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.tablasistema')),
                ('tipo_accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.tipoaccion')),
            ],
        ),
    ]
